import styled, { keyframes } from 'styled-components';
import { Text, Button } from '.';

const Card = ({ advice, fetchAdvice }) => {
  return (
    <Container /*key={`card-${advice.id}`}*/>
      <Text advice={advice} />
      <Button fetchAdvice={fetchAdvice} />
    </Container>
  );
};

export default Card;

const cardAnimation = keyframes`
  /* ----------------------------------------------
  * Generated by Animista on 2023-6-8 18:38:16
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation puff-in-center
  * ----------------------------------------
  */
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
    -webkit-filter: blur(4px);
    filter: blur(4px);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
`;

const Container = styled.div`
  font-family: 'Manrope', sans-serif;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  animation: ${cardAnimation} 0.5s cubic-bezier(0.47, 0, 0.745, 0.715) both;
`;
